[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.10"
hat = { version = "0.1.0", features = ["zbus"] }
hat-macros = { version = "0.1.0" }
panic-halt = "0.2.0"

[lib]
crate-type = ["staticlib"]
