// This file is automatically @generated by Tailor
// It is not inteded for manual editing.
#ifndef __BRIDGE_H__
#define __BRIDGE_H__

#define NUM_OF_TASKS 1

void main_task(void);

#endif /* __BRIDGE_H__ */
