// This file is automatically @generated by Tailor
// It is not inteded for manual editing.
#include <zephyr/kernel.h>
#include <zephyr/zbus/zbus.h>
#include "bridge.h"

K_THREAD_DEFINE(main_task_id, 1024, main_task, NULL, NULL, NULL, 3, 0, 0);
